<?php
  include "init_db.php";

  $queries = array();
  parse_str($_SERVER['QUERY_STRING'], $queries);
  $name = $queries["name"];

  $r = mysqli_query($db, "SELECT *
	FROM Log l
  WHERE l.`Sender` = $name
	ORDER BY e.`Date` ASC");
?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <link href='https://fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="normalize.css" />
  <link rel="stylesheet" type="text/css" href="index.css" />

  <title>Logs</title>
</head>

<body>
  <div class="container-parent">
    <div class="container">
      <h1 style="margin-bottom:12px;">
        Logs generated by facility (10)
      </h1>
      <div style="font-size:20px">
        <?php
        echo("Sender: ".$name);
        ?>
      </div>

      <table border='1'>
      <tr>
        <th>ID</th>
        <th>Last Name</th>
        <th>Date</th>
        <th>Receiver</th>
        <th>Sender</th>
        <th>Subject</th>
        <th>Body</th>
      </tr>
      <?php
      while(true) {
        $assoc = mysqli_fetch_assoc($r);
        if($assoc == null) {
          break;
        }
        echo("<tr><td>".$assoc["ID"]."</td>"
        ."<td>".$assoc["Last Name"]."</td>"
        ."<td>".$assoc["Date"]."</td>"
        ."<td>".$assoc["Receiver"]."</td>"
        ."<td>".$assoc["Sender"]."</td>"
        ."<td>".$assoc["Subject"]."</td>"
        ."<td>".$assoc["Body"]."</td></tr>");
      }
      ?>  
      </table>
    </div>
  </div>
</body>

</html>